maintainers:
  - agc93
  - daveaglick
  - devlead
  - ecampidoglio
  - gep13
  - jericho
  - mholo65
  - pascalberger
  - patriksvensson

features:
  - comments
  - pr_description_required
  - no_newbies # Enable for Hacktoberfest

contributing_url: https://github.com/cake-build/website#contributing
